[package]
name = "choir"
version = "0.4.1"
edition = "2021"
description = "Task Orchestration Framework"
license = "MIT"
documentation = "https://docs.rs/choir"
repository = "https://github.com/kvark/choir"
keywords = ["job-system", "tasks"]
categories = ["concurrency", "game-development"]

[workspace]
members = [
	"apps",
]

[features]
loom = ["loom-crate", "synqueue/loom"]

[[bench]]
name = "ballpark"
harness = false

[dependencies]
# https://github.com/crossbeam-rs/crossbeam/issues/846
#crossbeam-deque = "0.8"
synqueue = { git = "https://github.com/kvark/synqueue", rev = "a6d18f3" }
log = "0.4"
loom-crate = { package = "loom", version = "0.5.6", features = ["checkpoint"], optional = true }
profiling = "1"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"
num_cpus = "1"
