[package]
name = "choir"
version = "0.4.1"
edition = "2021"
description = "Task Orchestration Framework"
license = "MIT"
documentation = "https://docs.rs/choir"
repository = "https://github.com/kvark/choir"
keywords = ["job-system", "tasks"]
categories = ["concurrency", "game-development"]

[workspace]
members = [
	"apps",
]

[[bench]]
name = "ballpark"
harness = false

[dependencies]
crossbeam-deque = "0.8"
log = "0.4"
#loom = { git = "https://github.com/tokio-rs/loom", rev="d0c1e7108a0f8e0a397f3ad32a7e7e650b2db71e", optional = true }
loom = { path = "../loom", features = ["checkpoint"], optional = true }
profiling = "1"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.9"
num_cpus = "1"
